apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: abc-php-example
  template: abc-php-example
message: |-
  The following service(s) have been created in your project: ${NAME}.
  For more information about using this template, see Yannick
metadata:
  annotations:
    description: |-
      An example of PHP application deploy from an existing container image.
    iconClass: icon-php
    tags: quickstart,php
    openshift.io/documentation-url: https://put_your_readme_url
    openshift.io/long-description: This template defines resources needed to the existing ABC application.
    openshift.io/provider-display-name: ABC, Inc.
    openshift.io/support-url: https://put_your_readme_url   
    template.openshift.io/bindable: "false"    
  labels:
    samples.operator.openshift.io/managed: "true"    
  name: abc-php-example
  namespace: openshift
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: ${NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${NAME}      
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${NAME}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    dockerImageRepository: ${IMAGE_ARTIFACTORY_LOCATION}
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ${IMAGE_ARTIFACTORY_LOCATION}
      name: latest
      referencePolicy:
        type: Source      
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application 
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600      
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${NAME}
          from:
            kind: ImageStreamTag
            name: '${NAME}:latest'
      - type: ConfigChange
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}    
      spec:
        containers:
        - env: []
          image: ${IMAGE_ARTIFACTORY_LOCATION}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
          name: ${NAME}
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 3
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
              cpu: ${CPU_LIMIT}
            requests:
              memory: ${RES_MEMORY_LIMIT}
              cpu: ${RES_CPU_LIMIT}
          volumeMounts:
          - mountPath: /data/config.json
            name: ${NAME}-config
            subPath: config.json    
        volumes:
          - name: ${NAME}-config
            projected:
              sources:
              - configMap:
                  name: ${NAME}-config
                  items:
                    - key: config.json
                      path: config.json
                  defaultMode: 420
parameters:
- description: The name assigned to all of the ABC Inc. Application objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: ABC-APP-NAME
- description: Artifactory Image location and tag
  displayName: Artifactory Image location and tag
  name: IMAGE_ARTIFACTORY_LOCATION
  value: docker.io/appuio/example-php-docker-helloworld
  required: true 
- description: Reserved amount of memory the Application container can use.
  displayName: Reserved Memory Limit in Meg(Mi) or Gig (Gi)
  name: RES_MEMORY_LIMIT
  required: true
  value: 256Mi
- description: Reserved amount of cpu the Application container can use.
  displayName: Reserved Cpu Limit in Milicore(m) or a full CPU count (1)
  name: RES_CPU_LIMIT
  required: true
  value: 100m
- description: Maximum amount of memory the Application container can use.
  displayName: Maximum Memory Limit in Meg(Mi) or Gig (Gi)
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: Maximum amount of cpu the Application container can use.
  displayName: Maximum Cpu Limit in Milicore(m) or a full CPU count (1)
  name: CPU_LIMIT
  required: true
  value: 250m    
- description: The exposed hostname that will route to the abc inc. Application service, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN

